config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/about'
  root 'home#index'
  resources :projects
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:project_name, :project_description, :date_created)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
        <img style="width: 200px;" src="https://rupee.com.br/wp-content/uploads/2022/01/RUPEE-Solutions-LOGO-400.png" />
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "About", home_about_path, class:"nav-link" %> 
        </li>
        <li class="nav-item">
          <%= link_to "Projects", projects_path, class:"nav-link" %> 
        </li>
        

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Add Project", new_project_path, class:"nav-link" %> 
          </li>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %> 
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, data: {turbo_method: :delete}, class:"nav-link" %> 
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log In", new_user_session_path, class:"nav-link" %> 
          </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<br/><h3>Rupee Solutions project management dashboard</h3>

app/views/home/index.html.erb
<div class="mx-auto" style="width: 400px;">
    <img class="img-fluid rounded mx-auto d-block" src="https://www.pro-manchester.co.uk/wp-content/uploads/2021/06/Rupee-logo.png" />
</div>
<div class="text-center">
    <h1>Project Manager</h1><br/>
    <%= link_to "View Projects", projects_path, class:"btn btn-primary" %>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice =%>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Project Manager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'home/header' %>
    <br/>
    <div class="container">
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
    
      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group mb-3">
    <%= form.text_field :project_name, class:"form-control", placeholder:"Project Name" %>
  </div>

  <div class="field form-group mb-3">
    <%= form.text_area :project_description, class:"form-control", placeholder:"Description" %>
  </div>

  <div class="field form-group mb-3">
    <%= form.datetime_field :date_created, class:"form-control" %>
  </div>
  <br/>
  <div>
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Project name:</strong>
    <%= project.project_name %>
  </p>

  <p>
    <strong>Project description:</strong>
    <%= project.project_description %>
  </p>

  <p>
    <strong>Date created:</strong>
    <%= project.date_created %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>
<br>
<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show This Project", @project, class:"btn btn-primary" %> 
  <%= link_to "Back To Projects", projects_path, class:"btn btn-dark" %>
</div>

app/views/projects/index.html.erb
<br/><div id="projects">
  <table class="table table-striped table-hover">
    <thead class="table-dark">
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Date Created</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
      <% @projects.each do |project| %>
      <tr>
          <td><%= project.project_name %></td>
          <td><%= project.project_description %></td>
          <td><%= project.date_created %></td>         
          <td><%= link_to "Show", project, class:"text-decoration-none" %></td>
          <td><%= link_to "Edit", edit_project_path(project), class:"text-decoration-none" %></td>
          <td><%= button_to "Destroy", project, method: :delete, class:"btn btn-danger btn-sm p-0" %></td>
      </tr> 
      <% end %>
  </tbody>
</table>
<%= link_to 'New Project', new_project_path, class:"btn btn-secondary" %>
  
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>
<br/>
<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back To Projects", projects_path, class:"btn btn-dark" %>
</div>

app/views/projects/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @project.project_name %></h1>
  <p class="lead"><%= @project.project_description %></p>
  <p class="lead"><%= @project.date_created %></p>
  <hr class="my-4">
  <p class="lead"><br /> 
    <%= link_to "Back To Projects", projects_path, class:"btn btn-secondary btn-lg" %>
    <%= link_to "Edit This Project", edit_project_path(@project), class:"btn btn-primary btn-lg" %>
    <%= button_to "Destroy This Project", @project, method: :delete, class:"btn btn-danger btn-lg" %>
  </p>
</div>